version: "3.8"
networks:
  services:
    external: true
  rabbitmq-network:
    external: true

services:
  sheet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - /app/.venv
    networks:
      - services
      - rabbitmq-network
    depends_on:
      - db
    expose:
      - 8001
    command: >
      sh -c "
      python main.py
      "
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spreadsheet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - services


volumes:
  postgres_data: