version: "1"
networks:
  services:
    external: true
  rabbitmq-network:
    external: true
      
services:
  sheet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - /app/.venv
    networks:
      - services
      - rabbitmq-network
    expose:
      - 8001
    command: >
      sh -c "
      python main.py
      "